<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
		<TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
		<IsPackable>false</IsPackable>
		<DefaultItemExcludes>$(DefaultItemExcludes);node_modules\**</DefaultItemExcludes>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="3.1.18" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.32" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.32" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.32">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.5" />
		<PackageReference Include="Najiz.ApplicationInsights" Version="3.55.3" />
		<PackageReference Include="Najiz.DataProtection.keyStorage.Abstractions" Version="3.55.3" />
		<PackageReference Include="Najiz.Framework" Version="3.55.3" />
		<PackageReference Include="Najiz.Framework.DistributedCaching" Version="3.55.3" />
		<PackageReference Include="Najiz.Framework.Web" Version="3.55.3" />
		<PackageReference Include="Najiz.Integrations.ReCaptcha" Version="3.55.3" />
		<PackageReference Include="Najiz.NLog.Web" Version="3.55.3" />
		<PackageReference Include="Najiz.Web.Security" Version="3.55.3" />
		<PackageReference Include="Najiz.Web.Security.JwtBearer" Version="3.55.3" />
		<PackageReference Include="VueCliMiddleware" Version="3.1.2" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="App_Data\logs\**" />
		<Compile Remove="dist\**" />
		<Compile Remove="wwwroot\**" />
		<Content Remove="App_Data\logs\**" />
		<Content Remove="dist\**" />
		<Content Remove="wwwroot\**" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Remove="App_Data\logs\**" />
		<EmbeddedResource Remove="dist\**" />
		<EmbeddedResource Remove="wwwroot\**" />
		<None Remove="App_Data\logs\**" />
		<None Remove="dist\**" />
		<None Remove="wwwroot\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Remove="package.json" />
		<Content Remove="tslint.json" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="ClientApp\plugins\i18n.ts" />
		<None Remove="ClientApp\Services\TelemetryService.ts" />
	</ItemGroup>

	<ItemGroup>
		<None Include="package.json" />
		<None Include="public\manifest.json" />
		<None Include="tsconfig.json" />
		<None Include="tslint.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Config\NLog.config">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="ClientApp\public\" />
		<Folder Include="Controller\" />
		<Folder Include="MapperProfiles\" />
		<Folder Include="Models\" />
	</ItemGroup>

	<ItemGroup>
		<TypeScriptCompile Include="ClientApp\plugins\i18n.ts" />
		<TypeScriptCompile Include="ClientApp\Services\TelemetryService.ts" />
	</ItemGroup>

	<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
		<Exec WorkingDirectory="" Command="npm config set registry https://najizportalnpm.azurewebsites.net/" />
		<Exec WorkingDirectory="" Command="npm install" />
		<Exec WorkingDirectory="" Command="npm run build" />

		<ItemGroup>
			<DistFiles Include="dist\**" />
			<ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
				<RelativePath>%(DistFiles.Identity)</RelativePath>
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
			</ResolvedFileToPublish>
		</ItemGroup>
	</Target>
</Project>
